"""error corregido

Revision ID: ce5b6182db97
Revises: 27c100eeb09e
Create Date: 2023-07-10 17:41:56.885491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5b6182db97'
down_revision = '27c100eeb09e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Noticias', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('subtitulo',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('resaltado',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('columna1',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=3000),
               existing_nullable=False)
        batch_op.alter_column('columna2',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=3000),
               existing_nullable=False)
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Noticias', schema=None) as batch_op:
        batch_op.alter_column('categoria',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.alter_column('columna2',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
        batch_op.alter_column('columna1',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
        batch_op.alter_column('resaltado',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('subtitulo',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
